services:
  - type: web
    name: assessment-microservice
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-backend/DataSaverMicroservice/Dockerfile
    dockerContext: ./cervicare-backend/DataSaverMicroservice
    buildCommand: ./mvnw clean package -DskipTests
    plan: free
    region: oregon
    envVars:
      - fromGroup: sqlvariable
      - key: PORT
        value: 8080

  - type: web
    name: appointment
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-backend/appointment/Dockerfile
    dockerContext: ./cervicare-backend/appointment
    buildCommand: ./mvnw clean package -DskipTests
    plan: free
    region: oregon
    envVars:
      - fromGroup: sqlvariable
      - key: PORT
        value: 8081

  - type: web
    name: cervicare-user-service
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-backend/Cervicare_user_service/Dockerfile
    dockerContext: ./cervicare-backend/Cervicare_user_service
    buildCommand: ./mvnw clean package -DskipTests
    plan: free
    region: oregon
    envVars:
      - fromGroup: sqlvariable
      - key: PORT
        value: 8082

  - type: web
    name: hospital-recommender-service
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-backend/hospital-recommender-service/Dockerfile
    dockerContext: ./cervicare-backend/hospital-recommender-service
    buildCommand: ./mvnw clean package -DskipTests
    plan: free
    region: oregon
    envVars:
      - fromGroup: sqlvariable
      - key: PORT
        value: 8083

  - type: web
    name: cervicare-frontend
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-frontend/Dockerfile
    dockerContext: ./cervicare-frontend
    plan: free
    region: oregon
