services:
  - type: web
    name: assessment-microservice
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-backend/DataSaverMicroservice/Dockerfile
    dockerContext: ./cervicare-backend/DataSaverMicroservice
    buildCommand: ./mvnw clean package -DskipTests
    plan: free
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromEnvVar: DATABASE_URL
      - key: SPRING_DATASOURCE_USERNAME
        fromEnvVar: DATABASE_USER
      - key: SPRING_DATASOURCE_PASSWORD
        fromEnvVar: DATABASE_PASSWORD
      - key: ML_API_RISK_URL
        value: https://cervicare-risk-api.onrender.com/risk
      - key: ML_API_RECOMMENDATION_URL
        value: https://cervicare-risk-api.onrender.com/recommendation
      - key: ALLOWED_ORIGIN
        value: https://cervicare-frontend.onrender.com

  - type: web
    name: appointment
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-backend/appointment/Dockerfile
    dockerContext: ./cervicare-backend/appointment
    buildCommand: ./mvnw clean package -DskipTests
    plan: free
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromEnvVar: DATABASE_URL
      - key: SPRING_DATASOURCE_USERNAME
        fromEnvVar: DATABASE_USER
      - key: SPRING_DATASOURCE_PASSWORD
        fromEnvVar: DATABASE_PASSWORD
      - key: ALLOWED_ORIGIN
        value: https://cervicare-frontend.onrender.com

  - type: web
    name: cervicare-user-service
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-backend/Cervicare_user_service/Dockerfile
    dockerContext: ./cervicare-backend/Cervicare_user_service
    buildCommand: ./mvnw clean package -DskipTests
    plan: free
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromEnvVar: DATABASE_URL
      - key: SPRING_DATASOURCE_USERNAME
        fromEnvVar: DATABASE_USER
      - key: SPRING_DATASOURCE_PASSWORD
        fromEnvVar: DATABASE_PASSWORD
      - key: JWT_SECRET
        fromEnvVar: JWT_SECRET
      - key: ALLOWED_ORIGIN
        value: https://cervicare-frontend.onrender.com

  - type: web
    name: hospital-recommender-service
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-backend/hospital-recommender-service/Dockerfile
    dockerContext: ./cervicare-backend/hospital-recommender-service
    buildCommand: ./mvnw clean package -DskipTests
    plan: free
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromEnvVar: DATABASE_URL
      - key: SPRING_DATASOURCE_USERNAME
        fromEnvVar: DATABASE_USER
      - key: SPRING_DATASOURCE_PASSWORD
        fromEnvVar: DATABASE_PASSWORD
      - key: ALLOWED_ORIGIN
        value: https://cervicare-frontend.onrender.com

  - type: web
    name: cervicare-risk-api
    env: python
    repo: https://github.com/Techgirlies/cervicare-risk-api
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host=0.0.0.0 --port=5000
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 5000

  - type: web
    name: cervicare-frontend
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-frontend/Dockerfile
    dockerContext: ./cervicare-frontend
    plan: free
    region: oregon
