services:
  - type: web
    name: assessment-microservice
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-backend/DataSaverMicroservice/Dockerfile
    dockerContext: ./cervicare-backend/DataSaverMicroservice
    buildCommand: ./mvnw clean package -DskipTests
    plan: free
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://${MYSQL_HOST}:3306/cervicare?useSSL=false&allowPublicKeyRetrieval=true
      - key: SPRING_DATASOURCE_USERNAME
        value: ${MYSQL_USER}
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${MYSQL_PASSWORD}

  - type: web
    name: appointment
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-backend/appointment/Dockerfile
    dockerContext: ./cervicare-backend/appointment
    buildCommand: ./mvnw clean package -DskipTests
    plan: free
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://${MYSQL_HOST}:3306/cervicare?useSSL=false&allowPublicKeyRetrieval=true
      - key: SPRING_DATASOURCE_USERNAME
        value: ${MYSQL_USER}
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${MYSQL_PASSWORD}

  - type: web
    name: cervicare-user-service
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-backend/Cervicare_user_service/Dockerfile
    dockerContext: ./cervicare-backend/Cervicare_user_service
    buildCommand: ./mvnw clean package -DskipTests
    plan: free
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://${MYSQL_HOST}:3306/cervicare?useSSL=false&allowPublicKeyRetrieval=true
      - key: SPRING_DATASOURCE_USERNAME
        value: ${MYSQL_USER}
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${MYSQL_PASSWORD}

  - type: web
    name: hospital-recommender-service
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-backend/hospital-recommender-service/Dockerfile
    dockerContext: ./cervicare-backend/hospital-recommender-service
    buildCommand: ./mvnw clean package -DskipTests
    plan: free
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://${MYSQL_HOST}:3306/cervicare?useSSL=false&allowPublicKeyRetrieval=true
      - key: SPRING_DATASOURCE_USERNAME
        value: ${MYSQL_USER}
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${MYSQL_PASSWORD}

  - type: web
    name: cervicare-frontend
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-frontend/Dockerfile
    dockerContext: ./cervicare-frontend
    plan: free
    region: oregon

databases:
  - name: cervicare-db
    databaseName: cervicare
    user: cervicare_user
    plan: free
    region: oregon
    envVars:
      - key: MYSQL_HOST
        fromDatabase:
          name: cervicare-db
          property: host
      - key: MYSQL_USER
        fromDatabase:
          name: cervicare-db
          property: user
      - key: MYSQL_PASSWORD
        fromDatabase:
          name: cervicare-db
          property: password
