services:
  - type: web
    name: assessment-microservice
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-backend/DataSaverMicroservice/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: cervicare-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: cervicare-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: cervicare-db
          property: password
    plan: free
    region: oregon

  - type: web
    name: appointment
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-backend/appointment/Dockerfile
    plan: free
    region: oregon

  - type: web
    name: cervicare-user-service
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-backend/Cervicare_user_service/Dockerfile
    plan: free
    region: oregon

  - type: web
    name: cervicare-risk-api
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-backend/cervicare-risk-api/Dockerfile
    plan: free
    region: oregon

  - type: web
    name: hospital-recommender-service
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./cervicare-backend/hospital-recommender-service/Dockerfile
    plan: free
    region: oregon

  - type: web
    name: cervicare-frontend
    env: docker
    repo: https://github.com/Techgirlies/Cervicare
    branch: main
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    region: oregon

databases:
  - name: cervicare-db
    databaseName: cervicare
    user: cervicare_user
    plan: free
    region: oregon
  